# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articlename', models.CharField(max_length=100, verbose_name='\u6587\u7ae0\u540d\u79f0')),
                ('articlepic', models.FileField(upload_to='imgs/%Y/%m/%d')),
                ('articletime', models.DateField(verbose_name='\u6587\u7ae0\u65e5\u671f')),
                ('articlecontent', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnname', models.CharField(max_length=100, verbose_name='\u680f\u76ee')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='articlecolumn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Column', verbose_name='\u680f\u76ee'),
        ),
        migrations.AddField(
            model_name='article',
            name='articleuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005'),
        ),
    ]
